# Generated by Django 6.1.1 on 2026-10-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vendor',
            field=models.BooleanField(default=False, help_text='Designates whether this user has vendor privileges (selected by Admin).'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
